//! Layout -> addon/WowKeys/Layout.lua, the data the WowKeys addon applies.

use crate::layout::{Action, Chord, Layout, pad_slot};
use std::collections::BTreeMap;

pub fn render(layout: &Layout) -> String {
    let modes: String = layout
        .modes
        .iter()
        .map(|m| {
            let key = match &m.banner {
                Some(b) => lua_str(&Chord::banner(b).wow()),
                None => "nil".into(),
            };
            format!(
                "    {{ name = {}, label = {}, key = {key} }},\n",
                lua_str(&m.name),
                lua_str(&m.label),
            )
        })
        .collect();

    let mut bindings = String::new();
    let mut buttons = Vec::new();
    let mut macros = BTreeMap::new();
    for mode in &layout.modes {
        for (key, action) in mode.keys_in_order() {
            let command = match action {
                Action::Switch(_) => continue,
                Action::Command(c) => c.clone(),
                Action::Button(b) => {
                    if let (Some(name), Some(body)) = (&b.macro_name, &b.body) {
                        macros.insert(name.clone(), body.clone());
                    }
                    if let Some((_, slot)) = b.slot() {
                        let what = match (&b.spell, &b.macro_name) {
                            (Some(spell), _) => Some(format!("spell = {}", lua_str(spell))),
                            (_, Some(name)) => Some(format!("macro = {}", lua_str(name))),
                            _ => None,
                        };
                        if let Some(what) = what {
                            buttons.push((slot, format!("    {{ slot = {slot}, {what} }},\n")));
                        }
                    }
                    b.command()
                }
            };
            bindings.push_str(&format!(
                "    {{ {}, {} }},\n",
                lua_str(&mode.chord(key).wow()),
                lua_str(&command)
            ));
        }
    }

    for b in &layout.steam_buttons {
        bindings.push_str(&format!(
            "    {{ {}, {} }},\n",
            lua_str(&b.chord().wow()),
            lua_str(&b.command)
        ));
    }

    for (layer, inputs) in &layout.controller {
        for (input, b) in inputs {
            let slot = pad_slot(layer, input).expect("validated controller slot");
            if let (Some(name), Some(body)) = (&b.macro_name, &b.body) {
                macros.insert(name.clone(), body.clone());
            }
            let what = match (&b.spell, &b.macro_name) {
                (Some(spell), _) => format!("spell = {}", lua_str(spell)),
                (_, Some(name)) => format!("macro = {}", lua_str(name)),
                _ => continue,
            };
            buttons.push((slot, format!("    {{ slot = {slot}, {what} }},\n")));
        }
    }

    buttons.sort();
    buttons.dedup();
    let buttons: String = buttons.into_iter().map(|(_, line)| line).collect();
    let macros: String = macros
        .iter()
        .map(|(name, body)| format!("    {{ {}, {} }},\n", lua_str(name), lua_str(body)))
        .collect();
    let cvars: String = layout
        .cvars
        .iter()
        .map(|(name, value)| format!("    {{ {}, {} }},\n", lua_str(name), lua_str(value)))
        .collect();
    let revision = fnv1a(format!("{buttons}{macros}").as_bytes());

    format!(
        "-- GENERATED by layoutgen from layout.toml. Edit that, then `cargo run`.\n\
         WowKeysLayout = {{\n  \
           -- Changes when buttons or macros change; the addon re-places bars then.\n  \
           revision = {},\n  \
           modes = {{\n{modes}  }},\n  \
           bindings = {{\n{bindings}  }},\n  \
           buttons = {{\n{buttons}  }},\n  \
           macros = {{\n{macros}  }},\n  \
           cvars = {{\n{cvars}  }},\n\
         }}\n",
        lua_str(&format!("{revision:08x}")),
    )
}

fn lua_str(s: &str) -> String {
    let escaped = s
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n");
    format!("\"{escaped}\"")
}

/// Stable across Rust versions, unlike DefaultHasher.
fn fnv1a(bytes: &[u8]) -> u32 {
    bytes.iter().fold(0x811c_9dc5, |h, &b| {
        (h ^ u32::from(b)).wrapping_mul(0x0100_0193)
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn escapes_lua_strings() {
        assert_eq!(lua_str("a\"b\\c\nd"), r#""a\"b\\c\nd""#);
    }
}
