//! Layout -> addon/WowKeys/Layout.lua, the data the WowKeys addon applies.

use crate::layout::{Action, Chord, Layout};

pub fn render(layout: &Layout) -> String {
    let modes: String = layout
        .modes
        .iter()
        .map(|m| {
            format!(
                "    {{ name = {}, label = {}, key = {} }},\n",
                lua_str(&m.name),
                lua_str(&m.label),
                lua_str(&Chord::banner(&m.banner).wow()),
            )
        })
        .collect();

    let mut bindings = String::new();
    let mut buttons = Vec::new();
    for mode in &layout.modes {
        for (key, action) in mode.keys_in_order() {
            let command = match action {
                Action::Switch(_) => continue,
                Action::Command(c) => c.clone(),
                Action::Button(b) => {
                    let (command, slot) = b.target();
                    let what = match (&b.spell, &b.macro_name, &b.body) {
                        (Some(spell), _, _) => format!("spell = {}", lua_str(spell)),
                        (_, Some(name), Some(body)) => {
                            format!("macro = {}, body = {}", lua_str(name), lua_str(body))
                        }
                        _ => String::new(),
                    };
                    if !what.is_empty() {
                        buttons.push((slot, format!("    {{ slot = {slot}, {what} }},\n")));
                    }
                    command
                }
            };
            bindings.push_str(&format!(
                "    {{ {}, {} }},\n",
                lua_str(&mode.chord(key).wow()),
                lua_str(&command)
            ));
        }
    }

    buttons.sort();
    buttons.dedup();
    let buttons: String = buttons.into_iter().map(|(_, line)| line).collect();

    format!(
        "-- GENERATED by layoutgen from layout.toml. Edit that, then `cargo run`.\n\
         WowKeysLayout = {{\n  \
           -- Changes when the buttons change; the addon re-places bars then.\n  \
           revision = {},\n  \
           modes = {{\n{modes}  }},\n  \
           bindings = {{\n{bindings}  }},\n  \
           buttons = {{\n{buttons}  }},\n\
         }}\n",
        lua_str(&format!("{:08x}", fnv1a(buttons.as_bytes()))),
    )
}

fn lua_str(s: &str) -> String {
    let escaped = s
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n");
    format!("\"{escaped}\"")
}

/// Stable across Rust versions, unlike DefaultHasher.
fn fnv1a(bytes: &[u8]) -> u32 {
    bytes.iter().fold(0x811c_9dc5, |h, &b| {
        (h ^ u32::from(b)).wrapping_mul(0x0100_0193)
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn escapes_lua_strings() {
        assert_eq!(lua_str("a\"b\\c\nd"), r#""a\"b\\c\nd""#);
    }
}
