//! Layout -> kanata config.

use crate::keys::GRID;
use crate::layout::{Action, Chord, Layout, Mode, Switch};
use std::collections::BTreeMap;

pub fn render(layout: &Layout) -> String {
    let aliases = aliases(layout);

    let mut grids = vec![("defsrc".to_string(), grid(|k| k.to_string()))];
    for mode in &layout.modes {
        let cells = grid(|k| cell(layout, mode, k));
        grids.push((format!("deflayer {}", mode.name), cells));
    }
    let widths = column_widths(&grids);

    let mut out = String::from(HEADER);
    out.push_str("(defcfg\n  process-unmapped-keys yes\n)\n\n");
    out.push_str("(defalias\n");
    for (name, action) in &aliases {
        out.push_str(&format!("  {name} {action}\n"));
    }
    out.push_str(")\n");
    for (head, cells) in &grids {
        out.push_str(&format!("\n({head}\n"));
        for (row, row_widths) in cells.iter().zip(&widths) {
            let line: String = row
                .iter()
                .zip(row_widths)
                .map(|(c, w)| format!("{c:<w$} "))
                .collect();
            out.push_str(&format!("  {}\n", line.trim_end()));
        }
        out.push_str(")\n");
    }
    out
}

const HEADER: &str = "\
;; GENERATED by layoutgen from layout.toml. Edit that, then `cargo run`.
;;
;; Emergency exit (winIOv2 default): hold Left Ctrl + Space + Esc.

";

fn grid(f: impl Fn(&str) -> String) -> Vec<Vec<String>> {
    GRID.iter()
        .map(|row| row.iter().map(|k| f(k)).collect())
        .collect()
}

/// Widest cell per column across defsrc and every layer, so columns line up.
fn column_widths(grids: &[(String, Vec<Vec<String>>)]) -> Vec<Vec<usize>> {
    GRID.iter()
        .enumerate()
        .map(|(r, row)| {
            (0..row.len())
                .map(|c| grids.iter().map(|(_, g)| g[r][c].len()).max().unwrap_or(1))
                .collect()
        })
        .collect()
}

/// What a key does in a mode. Keys a mode doesn't map behave as in the home
/// (first) mode, so movement and mode keys work everywhere; passthrough
/// modes send them as typed instead.
fn cell(layout: &Layout, mode: &Mode, key: &str) -> String {
    let home = &layout.modes[0];
    match mode.keys.get(key) {
        None if mode.passthrough || std::ptr::eq(mode, home) => "_".into(),
        None => cell(layout, home, key),
        Some(Action::Switch(s)) => format!("@{}", switch_alias(mode, s)),
        // Game actions: plain key in unmodified modes, chord otherwise.
        Some(_) if mode.mods.is_empty() => "_".into(),
        Some(_) => mode.chord(key).kanata(),
    }
}

fn switch_alias(from: &Mode, s: &Switch) -> String {
    match &s.send {
        Some(send) => format!("{}-to-{}-{send}", from.name, s.mode),
        None => format!("{}-to-{}", from.name, s.mode),
    }
}

/// Banner chords plus one alias per distinct mode switch.
fn aliases(layout: &Layout) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    let mut targets = BTreeMap::new();
    for mode in &layout.modes {
        targets.insert(mode.name.as_str(), mode);
        if let Some(banner) = &mode.banner {
            out.insert(format!("bn-{}", mode.name), Chord::banner(banner).kanata());
        }
    }
    for from in &layout.modes {
        for action in from.keys.values() {
            let Action::Switch(s) = action else { continue };
            let target = targets[s.mode.as_str()];
            let action = match (target.oneshot, &target.banner) {
                // The next key reads this layer, then kanata drops back.
                (Some(ms), _) => format!("(one-shot {ms} (layer-while-held {}))", s.mode),
                (None, Some(_)) => {
                    // A passthrough mode has a text box open: send first
                    // (closing it), then the banner. Otherwise banner first,
                    // so it never lands in the box that `send` opens. `macro`
                    // taps in order, so Enter never picks up the banner's
                    // modifiers.
                    let banner = format!("@bn-{}", s.mode);
                    let taps = match (&s.send, from.passthrough) {
                        (None, _) => banner,
                        (Some(k), true) => format!("{k} {banner}"),
                        (Some(k), false) => format!("{banner} {k}"),
                    };
                    format!("(multi (layer-switch {}) (macro {taps}))", s.mode)
                }
                (None, None) => unreachable!("validated: non-one-shot modes have a banner"),
            };
            out.insert(switch_alias(from, s), action);
        }
    }
    out
}
