//! Layout -> kanata config.

use crate::keys::{self, GRID};
use crate::layout::{Action, Chord, Layout, Mode, Switch};
use std::collections::BTreeMap;

pub fn render(layout: &Layout) -> String {
    let (banners, switches) = aliases(layout);
    let mut os_forks = BTreeMap::new();

    let mut grids = vec![("defsrc".to_string(), grid(|k| k.to_string()))];
    for mode in &layout.modes {
        let cells = grid(|k| cell(layout, mode, k))
            .into_iter()
            .zip(GRID)
            .map(|(row, keys)| {
                row.into_iter()
                    .zip(keys.iter())
                    .map(|(c, k)| os_passthrough(layout, k, c, &mut os_forks))
                    .collect()
            })
            .collect();
        grids.push((format!("deflayer {}", mode.name), cells));
    }
    let widths = column_widths(&grids);

    let mut out = String::from(HEADER);
    out.push_str("(defcfg\n  process-unmapped-keys yes\n)\n\n");
    // kanata resolves aliases in declaration order: banners, then the
    // switches that use them, then the OS forks that wrap both.
    out.push_str("(defalias\n");
    for (name, action) in banners.iter().chain(&switches).chain(&os_forks) {
        out.push_str(&format!("  {name} {action}\n"));
    }
    out.push_str(")\n");
    for (head, cells) in &grids {
        out.push_str(&format!("\n({head}\n"));
        for (row, row_widths) in cells.iter().zip(&widths) {
            let line: String = row
                .iter()
                .zip(row_widths)
                .map(|(c, w)| format!("{c:<w$} "))
                .collect();
            out.push_str(&format!("  {}\n", line.trim_end()));
        }
        out.push_str(")\n");
    }
    out
}

const HEADER: &str = "\
;; GENERATED by layoutgen from layout.toml. Edit that, then `cargo run`.
;;
;; Emergency exit (winIOv2 default): hold Left Ctrl + Space + Esc.

";

fn grid(f: impl Fn(&str) -> String) -> Vec<Vec<String>> {
    GRID.iter()
        .map(|row| row.iter().map(|k| f(k)).collect())
        .collect()
}

/// Widest cell per column across defsrc and every layer, so columns line up.
fn column_widths(grids: &[(String, Vec<Vec<String>>)]) -> Vec<Vec<usize>> {
    GRID.iter()
        .enumerate()
        .map(|(r, row)| {
            (0..row.len())
                .map(|c| grids.iter().map(|(_, g)| g[r][c].len()).max().unwrap_or(1))
                .collect()
        })
        .collect()
}

/// What a key does in a mode. Keys a mode doesn't map behave as in the home
/// (first) mode, so movement and mode keys work everywhere; passthrough
/// modes send them as typed instead.
fn cell(layout: &Layout, mode: &Mode, key: &str) -> String {
    let home = &layout.modes[0];
    match mode.keys.get(key) {
        None if mode.passthrough || std::ptr::eq(mode, home) => "_".into(),
        None => cell(layout, home, key),
        Some(Action::Switch(s)) => format!("@{}", switch_alias(mode, s)),
        // Game actions: plain key in unmodified modes, chord otherwise.
        Some(_) if mode.mods.is_empty() => "_".into(),
        Some(_) => mode.chord(key).kanata(),
    }
}

/// Wraps a remapped key so it sends itself while an `os_hold` key is down
/// (Alt+Tab and friends), as an `os-` alias to keep the layers readable.
fn os_passthrough(layout: &Layout, key: &str, cell: String, aliases: &mut Aliases) -> String {
    if cell == "_" || layout.os_hold.is_empty() {
        return cell;
    }
    let name = match cell.strip_prefix('@') {
        // Several keys can share one switch alias (chat's Esc and Caps), and
        // each must fall back to itself, so the key is part of the name.
        Some(alias) => format!("os-{}-{alias}", keys::alias_safe(key)),
        // A chord like `A-C-;`: name it by its modifiers and a safe key name.
        None => format!(
            "os-{}{}",
            &cell[..cell.len() - key.len()],
            keys::alias_safe(key)
        ),
    };
    let fork = format!("(fork {cell} {key} ({}))", layout.os_hold.join(" "));
    aliases.insert(name.clone(), fork);
    format!("@{name}")
}

fn switch_alias(from: &Mode, s: &Switch) -> String {
    match &s.send {
        Some(send) => format!("{}-to-{}-{send}", from.name, s.mode),
        None => format!("{}-to-{}", from.name, s.mode),
    }
}

type Aliases = BTreeMap<String, String>;

/// Banner chords, and one alias per distinct mode switch.
fn aliases(layout: &Layout) -> (Aliases, Aliases) {
    let mut banners = BTreeMap::new();
    let mut out = BTreeMap::new();
    let mut targets = BTreeMap::new();
    for mode in &layout.modes {
        targets.insert(mode.name.as_str(), mode);
        if let Some(banner) = &mode.banner {
            banners.insert(format!("bn-{}", mode.name), Chord::banner(banner).kanata());
        }
    }
    for from in &layout.modes {
        for action in from.keys.values() {
            let Action::Switch(s) = action else { continue };
            let target = targets[s.mode.as_str()];
            let action = match (target.oneshot, &target.banner) {
                // The next key reads this layer, then kanata drops back.
                (Some(ms), _) => format!("(one-shot {ms} (layer-while-held {}))", s.mode),
                (None, Some(_)) => {
                    // A passthrough mode has a text box open: send first
                    // (closing it), then the banner. Otherwise banner first,
                    // so it never lands in the box that `send` opens. `macro`
                    // taps in order, so Enter never picks up the banner's
                    // modifiers.
                    let banner = format!("@bn-{}", s.mode);
                    let taps = match (&s.send, from.passthrough) {
                        (None, _) => banner,
                        (Some(k), true) => format!("{k} {banner}"),
                        (Some(k), false) => format!("{banner} {k}"),
                    };
                    format!("(multi (layer-switch {}) (macro {taps}))", s.mode)
                }
                (None, None) => unreachable!("validated: non-one-shot modes have a banner"),
            };
            out.insert(switch_alias(from, s), action);
        }
    }
    (banners, out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::layout;

    #[test]
    fn os_hold_keys_fall_back_to_themselves() {
        let layout = layout::parse(
            r#"
            os_hold = ["lalt"]
            [[mode]]
            name = "home"
            label = "HOME"
            banner = "f9"
            [mode.keys]
            ret = { mode = "chat", send = "ret" }
            [[mode]]
            name = "chat"
            label = "CHAT"
            banner = "f12"
            passthrough = true
            [mode.keys]
            esc = { mode = "home", send = "esc" }
            caps = { mode = "home", send = "esc" }
            "#,
        )
        .unwrap();
        let out = render(&layout);
        assert!(out.contains("os-esc-chat-to-home-esc (fork @chat-to-home-esc esc (lalt))"));
        assert!(out.contains("os-caps-chat-to-home-esc (fork @chat-to-home-esc caps (lalt))"));
        assert!(out.contains("os-ret-home-to-chat-ret (fork @home-to-chat-ret ret (lalt))"));
    }
}
