//! Layout -> kanata config.

use crate::keys::GRID;
use crate::layout::{Action, Chord, Layout, Mode, Switch};
use std::collections::BTreeMap;

pub fn render(layout: &Layout) -> String {
    let aliases = aliases(layout);

    let mut grids = vec![("defsrc".to_string(), grid(|k| k.to_string()))];
    for mode in &layout.modes {
        let cells = grid(|k| cell(mode, k));
        grids.push((format!("deflayer {}", mode.name), cells));
    }
    let widths = column_widths(&grids);

    let mut out = String::from(HEADER);
    out.push_str("(defcfg\n  process-unmapped-keys yes\n)\n\n");
    out.push_str("(defalias\n");
    for (name, action) in &aliases {
        out.push_str(&format!("  {name} {action}\n"));
    }
    out.push_str(")\n");
    for (head, cells) in &grids {
        out.push_str(&format!("\n({head}\n"));
        for (row, row_widths) in cells.iter().zip(&widths) {
            let line: String = row
                .iter()
                .zip(row_widths)
                .map(|(c, w)| format!("{c:<w$} "))
                .collect();
            out.push_str(&format!("  {}\n", line.trim_end()));
        }
        out.push_str(")\n");
    }
    out
}

const HEADER: &str = "\
;; GENERATED by layoutgen from layout.toml. Edit that, then `cargo run`.
;;
;; Emergency exit (winIOv2 default): hold Left Ctrl + Space + Esc.

";

fn grid(f: impl Fn(&str) -> String) -> Vec<Vec<String>> {
    GRID.iter()
        .map(|row| row.iter().map(|k| f(k)).collect())
        .collect()
}

/// Widest cell per column across defsrc and every layer, so columns line up.
fn column_widths(grids: &[(String, Vec<Vec<String>>)]) -> Vec<Vec<usize>> {
    GRID.iter()
        .enumerate()
        .map(|(r, row)| {
            (0..row.len())
                .map(|c| grids.iter().map(|(_, g)| g[r][c].len()).max().unwrap_or(1))
                .collect()
        })
        .collect()
}

fn cell(mode: &Mode, key: &str) -> String {
    match mode.keys.get(key) {
        None => "_".into(),
        Some(Action::Switch(s)) => format!("@{}", switch_alias(mode, s)),
        // Game actions: plain key in unmodified modes, chord otherwise.
        Some(_) if mode.mods.is_empty() => "_".into(),
        Some(_) => mode.chord(key).kanata(),
    }
}

fn switch_alias(from: &Mode, s: &Switch) -> String {
    match &s.send {
        Some(send) => format!("{}-to-{}-{send}", from.name, s.mode),
        None => format!("{}-to-{}", from.name, s.mode),
    }
}

/// Banner chords plus one alias per distinct mode switch.
fn aliases(layout: &Layout) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    for mode in &layout.modes {
        out.insert(
            format!("bn-{}", mode.name),
            Chord::banner(&mode.banner).kanata(),
        );
    }
    for from in &layout.modes {
        for action in from.keys.values() {
            let Action::Switch(s) = action else { continue };
            // A passthrough mode has a text box open: send first (closing it),
            // then the banner. Otherwise banner first, so it never lands in
            // the box that `send` opens. `macro` taps in order, so Enter
            // never picks up the banner's modifiers.
            let banner = format!("@bn-{}", s.mode);
            let taps = match (&s.send, from.passthrough) {
                (None, _) => banner,
                (Some(k), true) => format!("{k} {banner}"),
                (Some(k), false) => format!("{banner} {k}"),
            };
            out.insert(
                switch_alias(from, s),
                format!("(multi (layer-switch {}) (macro {taps}))", s.mode),
            );
        }
    }
    out
}
