//! Layout -> wow/steam-layers.md, the setup sheet for the Steam Input layer
//! that sends a keyboard mode's combos from the controller.

use crate::layout::{Action, Chord, Layout};

pub fn render(layout: &Layout) -> Option<String> {
    let steam = layout.steam_layer.as_ref()?;
    let mode = layout.modes.iter().find(|m| m.name == steam.mode)?;
    let home = &layout.modes[0];
    let enter = Chord::banner(mode.banner.as_deref()?).human();
    let leave = Chord::banner(home.banner.as_deref()?).human();

    let mut rows = String::new();
    for input in crate::layout::PAD_INPUTS {
        let Some(key) = steam.keys.get(*input) else {
            continue;
        };
        let what = match mode.keys.get(key) {
            Some(Action::Command(c)) => c.clone(),
            Some(Action::Button(b)) => b.spell.clone().or(b.macro_name.clone()).unwrap_or_default(),
            _ => continue,
        };
        rows.push_str(&format!(
            "| {} | {} | {what} |\n",
            input_name(input),
            mode.chord(key).human()
        ));
    }

    Some(format!(
        "<!-- GENERATED by layoutgen from layout.toml ([steam_layer]). Edit that, then `cargo run`. -->
# Steam Input: {label} layer on {button}

The controller's **{button}** button latches a Steam Input action layer
in which the controller sends the keyboard {label}-mode combos. WowKeys
already binds those combos, so nothing changes in WoW. Inputs not listed
keep their normal controller behaviour (Circle/B still closes windows).

Set up once in Steam: Battle.net in your library → Manage → Controller
layout.

1. **Action Layers → add a layer** named `WowKeys {label}`.
2. **Base layer, {button}:** command *Add Layer* `WowKeys {label}`, plus an
   extra command sending **{enter}** (shows `-- {label} --`).
3. **In the `WowKeys {label}` layer, {button}:** command *Remove Layer*
   `WowKeys {label}`, plus an extra command sending **{leave}** (shows
   `-- {home} --`).
4. **In the `WowKeys {label}` layer**, bind each input below to the keys
   shown (a keyboard key plus extra commands for Ctrl / Alt / Shift):

| Controller input | Send | Does |
|---|---|---|
{rows}
Release latched triggers before using the layer: inside windows the
triggers switch focus between frames.
",
        label = mode.label,
        home = home.label,
        button = steam.button,
    ))
}

fn input_name(input: &str) -> &'static str {
    match input {
        "left" => "D-pad Left",
        "up" => "D-pad Up",
        "right" => "D-pad Right",
        "down" => "D-pad Down",
        "west" => "Square / X",
        "north" => "Triangle / Y",
        "east" => "Circle / B",
        "south" => "Cross / A",
        _ => "?",
    }
}
