//! Layout -> wow/steam-layers.md, the Steam Input setup sheet: single
//! controller inputs that send one chord, and the action layer that sends a
//! keyboard mode's combos from the controller.

use crate::layout::{Action, Chord, Layout, SteamLayer};

pub fn render(layout: &Layout) -> Option<String> {
    let buttons = buttons_section(layout);
    let layer = layout
        .steam_layer
        .as_ref()
        .and_then(|steam| layer_section(layout, steam));
    if buttons.is_none() && layer.is_none() {
        return None;
    }
    Some(format!(
        "<!-- GENERATED by layoutgen from layout.toml ([[steam_button]], [steam_layer]). Edit that, then `cargo run`. -->
# Steam Input setup

Set up once in Steam: Battle.net in your library → Manage → Controller
layout. WowKeys already binds every combo below, so nothing changes in
WoW. Where a row says Ctrl / Alt / Shift, send the key plus extra
commands for those modifiers.
{}{}",
        buttons.unwrap_or_default(),
        layer.unwrap_or_default()
    ))
}

fn buttons_section(layout: &Layout) -> Option<String> {
    if layout.steam_buttons.is_empty() {
        return None;
    }
    let rows: String = layout
        .steam_buttons
        .iter()
        .map(|b| format!("| {} | {} | {} |\n", b.input, b.chord().human(), b.does))
        .collect();
    Some(format!(
        "
## Single buttons

Each input sends one combo.

| Controller input | Send | Does |
|---|---|---|
{rows}"
    ))
}

fn layer_section(layout: &Layout, steam: &SteamLayer) -> Option<String> {
    let mode = layout.modes.iter().find(|m| m.name == steam.mode)?;
    let home = &layout.modes[0];
    let enter = Chord::banner(mode.banner.as_deref()?).human();
    let leave = Chord::banner(home.banner.as_deref()?).human();

    let mut rows = String::new();
    for input in crate::layout::PAD_INPUTS {
        let Some(key) = steam.keys.get(*input) else {
            continue;
        };
        let what = match mode.keys.get(key) {
            Some(Action::Command(c)) => c.clone(),
            Some(Action::Button(b)) => b.spell.clone().or(b.macro_name.clone()).unwrap_or_default(),
            _ => continue,
        };
        rows.push_str(&format!(
            "| {} | {} | {what} |\n",
            input_name(input),
            mode.chord(key).human()
        ));
    }

    Some(format!(
        "
## {label} layer on {button}

The controller's **{button}** button latches a Steam Input action layer
in which the controller sends the keyboard {label}-mode combos. Inputs not
listed keep their normal controller behaviour (Circle/B still closes
windows).

1. **Action Layers → add a layer** named `WowKeys {label}`.
2. **Base layer, {button}:** command *Add Layer* `WowKeys {label}`, plus an
   extra command sending **{enter}** (shows `-- {label} --`).
3. **In the `WowKeys {label}` layer, {button}:** command *Remove Layer*
   `WowKeys {label}`, plus an extra command sending **{leave}** (shows
   `-- {home} --`).
4. **In the `WowKeys {label}` layer**, bind each input below:

| Controller input | Send | Does |
|---|---|---|
{rows}
Release a latched trigger before using the layer: inside windows the
triggers switch focus between frames.
",
        label = mode.label,
        home = home.label,
        button = steam.button,
    ))
}

fn input_name(input: &str) -> &'static str {
    match input {
        "left" => "D-pad Left",
        "up" => "D-pad Up",
        "right" => "D-pad Right",
        "down" => "D-pad Down",
        "west" => "Square / X",
        "north" => "Triangle / Y",
        "east" => "Circle / B",
        "south" => "Cross / A",
        _ => "?",
    }
}
