//! Layout -> wow/steam-layers.md, the Steam Input setup sheet: controller
//! inputs that each send one key, in the base layout or in a Steam layer
//! one button toggles.

use crate::layout::{Layout, SteamButton, SteamLayer};

pub fn render(layout: &Layout) -> Option<String> {
    if layout.steam_buttons.is_empty() {
        return None;
    }
    let base: Vec<&SteamButton> = layout
        .steam_buttons
        .iter()
        .filter(|b| b.layer.is_none())
        .collect();
    let layer = layout
        .steam_layer
        .as_ref()
        .map(|l| layer_section(layout, l))
        .unwrap_or_default();
    Some(format!(
        "<!-- GENERATED by layoutgen from layout.toml ([[steam_button]], [steam_layer]). Edit that, then `cargo run`. -->
# Steam Input setup

Set up once in Steam: Battle.net in your library → Manage → Controller
layout. Each input below sends one key; WowKeys binds that key in WoW, so
nothing else needs setting up there. Inputs not listed keep their normal
controller behaviour.

## Base layout

{}{layer}",
        table(&base)
    ))
}

fn layer_section(layout: &Layout, layer: &SteamLayer) -> String {
    let buttons: Vec<&SteamButton> = layout
        .steam_buttons
        .iter()
        .filter(|b| b.layer.as_deref() == Some(layer.name.as_str()))
        .collect();
    format!(
        "
## {name} layer on {button}

**{button}** toggles a Steam action layer. While it's on, the inputs below
open windows; everything else stays native, so inside a window the
sticks move, Cross/A accepts, Circle/B cancels and the bumpers change
tabs, as Blizzard's Gamepad UI intends.

1. **Action Layers → add a layer** named `{name}`.
2. **Base layout, {button}:** *Add Layer* `{name}`.
3. **In the `{name}` layer, {button}:** *Remove Layer* `{name}`.
4. **In the `{name}` layer**, bind each input below to its key.
5. Recommended: give each input below a **sub command** *Remove Layer*
   `{name}` (Steam's sub commands add more outputs to the same press).
   Then one press opens the window and drops you back to your normal
   controller, so the D-pad can't be left opening windows when a fight
   starts.

{}
Keep Num Lock on, in case Steam sends the keypad keys as scan codes.
",
        table(&buttons),
        name = layer.name,
        button = layer.button,
    )
}

fn table(buttons: &[&SteamButton]) -> String {
    let rows: String = buttons
        .iter()
        .map(|b| format!("| {} | {} | {} |\n", b.input, b.chord().human(), b.does))
        .collect();
    format!("| Controller input | Key | Does |\n|---|---|---|\n{rows}")
}
